import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import loggedIn from "../util/authGuard";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loggedIn ? <Home /> : <div>Login</div>}
    </div>
  );
}
